use std::path::Path;
use plowrt::asset::devblob::DevBlob;
use plowrt::exec::ctx_bound::widen;

#[test]
fn gemma4_differential_widen_8k_to_32k_matches_native_32k() {
    let p8 = Path::new("/tmp/gemma4_test_8k/model.pkt");
    let p32 = Path::new("/tmp/gemma4_test_32k/model.pkt");

    let hf_dir = Path::new("/opt/dlami/nvme/hf-cache/hub/models--google--gemma-4-12B-it/snapshots/707f0a3b8a3c7ad586ed01e27eafbad8a27dd0f7");
    if (!p8.exists() || !p32.exists()) && hf_dir.exists() {
        if !p8.exists() {
            let status = std::process::Command::new("cargo")
                .args([
                    "run", "-p", "plowc", "--",
                    "--hf-dir", hf_dir.to_str().unwrap(),
                    "--gpu", "H100 SXM5",
                    "--arch", "sm_90a",
                    "--n-cu", "132",
                    "--emit", "devblob",
                    "--max-ctx", "8192",
                    "--out", "/tmp/gemma4_test_8k",
                    "--segmented",
                ])
                .status()
                .expect("failed to emit 8k packet");
            assert!(status.success());
        }
        if !p32.exists() {
            let status = std::process::Command::new("cargo")
                .args([
                    "run", "-p", "plowc", "--",
                    "--hf-dir", hf_dir.to_str().unwrap(),
                    "--gpu", "H100 SXM5",
                    "--arch", "sm_90a",
                    "--n-cu", "132",
                    "--emit", "devblob",
                    "--max-ctx", "32768",
                    "--out", "/tmp/gemma4_test_32k",
                    "--segmented",
                ])
                .status()
                .expect("failed to emit 32k packet");
            assert!(status.success());
        }
    }

    if !p8.exists() || !p32.exists() {
        eprintln!("skip: test packets /tmp/gemma4_test_8k or 32k not present and hf-cache not found");
        return;
    }

    let b8_bytes = std::fs::read(p8).unwrap();
    let b32_bytes = std::fs::read(p32).unwrap();

    let mut b8 = DevBlob::parse(&b8_bytes).unwrap();
    let b32 = DevBlob::parse(&b32_bytes).unwrap();

    let m8 = b8.with_packet_view(plow_asset::live_kv::emit).unwrap();
    let m32 = b32.with_packet_view(plow_asset::live_kv::emit).unwrap();

    let widened_bound = widen(&mut b8, 32768, Some(&m8)).expect("widen should succeed");
    assert_eq!(widened_bound, 32768);

    // 1. Live KV manifest caches match
    let m8_widened = b8.with_packet_view(plow_asset::live_kv::emit).unwrap();
    assert_eq!(m8_widened.caches.len(), m32.caches.len(), "cache count matches");
    assert_eq!(m8_widened.caches, m32.caches, "all live KV caches match");

    // 2. Tensor names, sizes, and layout match
    assert_eq!(b8.tensors.len(), b32.tensors.len(), "tensor count matches");
    for (t_w, t_n) in b8.tensors.iter().zip(b32.tensors.iter()) {
        assert_eq!(t_w.name, t_n.name, "tensor name matches");
        assert_eq!(t_w.bytes, t_n.bytes, "tensor bytes match for {}", t_w.name);
    }

    // 3. RoPE cos/sin table recipes and generated bytes match
    assert_eq!(b8.gen.len(), b32.gen.len(), "gen tensor recipes match");
    for (g_w, g_n) in b8.gen.iter().zip(b32.gen.iter()) {
        assert_eq!(g_w.kind, g_n.kind);
        assert_eq!(g_w.ctx, g_n.ctx);
        assert_eq!(g_w.hd, g_n.hd);
        assert_eq!(g_w.byte_len(), g_n.byte_len());
        if packet::ctx_bound::is_rope_recipe(g_w) {
            let bytes_w = g_w.generate().expect("materialize widened rope");
            let bytes_n = g_n.generate().expect("materialize native rope");
            assert_eq!(bytes_w, bytes_n, "rope bytes match for kind {}", g_w.kind);
        }
    }

    // 4. Stride sites match
    let flash_decode = packet::dev::DevOp::FlashDecode as u16;
    let flash_decode_fp8 = packet::dev::DevOp::FlashDecodeFp8 as u16;
    let flash_prefill = packet::dev::DevOp::FlashPrefill as u16;
    let flash_prefill_fp8 = packet::dev::DevOp::FlashPrefillFp8 as u16;
    let head_norm_rope = packet::dev::DevOp::HeadNormRope as u16;

    assert_eq!(b8.progs.len(), b32.progs.len(), "program count matches");
    for (p_idx, (p_w, p_n)) in b8.progs.iter().zip(b32.progs.iter()).enumerate() {
        assert_eq!(p_w.t, p_n.t, "prog {} T matches", p_idx);
        assert_eq!(p_w.insts.len(), p_n.insts.len(), "prog {} inst len matches", p_idx);

        for (i_idx, (inst_w, inst_n)) in p_w.insts.iter().zip(p_n.insts.iter()).enumerate() {
            let op = inst_w.op;
            assert_eq!(op, inst_n.op, "prog {} inst {} op matches", p_idx, i_idx);

            if op == flash_decode || op == flash_decode_fp8 {
                assert_eq!(
                    inst_w.i[3], inst_n.i[3],
                    "prog {} inst {} FlashDecode kv_stride matches", p_idx, i_idx
                );
            } else if op == flash_prefill || op == flash_prefill_fp8 {
                assert_eq!(
                    inst_w.fj[1], inst_n.fj[1],
                    "prog {} inst {} FlashPrefill kv_stride matches", p_idx, i_idx
                );
            } else if op == head_norm_rope {
                assert_eq!(
                    inst_w.fj[1], inst_n.fj[1],
                    "prog {} inst {} HeadNormRope out_stride matches", p_idx, i_idx
                );
            }
        }
    }

    // 5. Ladder programs match
    for (p_idx, (p_w, p_n)) in b8.progs.iter().zip(b32.progs.iter()).enumerate() {
        assert_eq!(p_w.t, p_n.t);
        assert_eq!(p_w.gq_seg_ofs, p_n.gq_seg_ofs, "prog {} gq_seg_ofs matches", p_idx);
        assert_eq!(p_w.insts.len(), p_n.insts.len(), "prog {} inst len matches", p_idx);

        for (i_idx, (iw, inat)) in p_w.insts.iter().zip(p_n.insts.iter()).enumerate() {
            assert_eq!(iw.op, inat.op, "prog {} inst {} op matches", p_idx, i_idx);
            assert_eq!(iw.blocks, inat.blocks, "prog {} inst {} blocks match", p_idx, i_idx);
            assert_eq!(iw.t, inat.t, "prog {} inst {} tensor operands match", p_idx, i_idx);

            if iw.op == flash_decode || iw.op == flash_decode_fp8 {
                // FlashDecode: i[0..5] = [batch, heads, kvh, kv_stride, window, nsplit]
                // i[6..8] = [hd, kvm]
                assert_eq!(iw.i[0], inat.i[0], "FlashDecode batch matches");
                assert_eq!(iw.i[1], inat.i[1], "FlashDecode heads matches");
                assert_eq!(iw.i[2], inat.i[2], "FlashDecode kvh matches");
                assert_eq!(iw.i[3], inat.i[3], "FlashDecode kv_stride matches");
                assert_eq!(iw.i[4], inat.i[4], "FlashDecode window matches");
                assert_eq!(iw.i[6], inat.i[6], "FlashDecode hd matches");
                assert_eq!(iw.i[7], inat.i[7], "FlashDecode kvm matches");
                // i[5] (nsplit) is emitted from compile-time max_ctx fallback; at runtime
                // PLOW_NV_NS_LIVE dynamically patches it from live kv_len.
                assert_eq!(iw.fj[0], inat.fj[0], "FlashDecode attn_scale matches");
                assert_eq!(iw.fj[2], inat.fj[2]);
                // NV bounds trap capacity: t * kvh * stride matches native
                assert_eq!(iw.fj[1], inat.fj[1]);
            } else if iw.op == packet::dev::DevOp::FlashMerge as u16 {
                // FlashMerge: i = [batch, heads, nsplit, hd, 0, 0, 0, 0]
                assert_eq!(iw.i[0], inat.i[0], "FlashMerge batch matches");
                assert_eq!(iw.i[1], inat.i[1], "FlashMerge heads matches");
                assert_eq!(iw.i[3], inat.i[3], "FlashMerge hd matches");
                assert_eq!(iw.i[4..], inat.i[4..]);
                assert_eq!(iw.fj, inat.fj);
            } else {
                // All other instructions must match bit-for-bit
                assert_eq!(
                    iw, inat,
                    "prog {} (T={}) inst {} (op={:?}) differs between widened and native",
                    p_idx, p_w.t, i_idx, packet::dev::DevOp::from_u16(iw.op)
                );
            }
        }
    }
}
