/* op_dsa_pool.h — GLM-5.3-Flash's DSA indexer key-pooling (`index_kpool`), ops 123/124.
 *
 * Ported from vLLM's real reference Triton kernels (`amd/ops/kpool_compress.py` in the
 * vendor image), not derived from prose. `d_dsa_pool_compress` verified against a
 * numerical oracle GENERATED BY RUNNING THAT REAL KERNEL on this box's GPU — see the
 * campaign notes under `perf-data/` for the exact numbers and how they were produced.
 * Full packet contract: `DevOp::DsaPoolCompress`/`DsaPoolExpand`'s doc comments in
 * `crates/packet/src/dev.rs`, mirrored in `runtime/common/dev_isa.h`.
 *
 * ONE WORKGROUP PER POOL for compress. Threads 0..head_dim-1 (128) do real work; the
 * softmax step is EMBARRASSINGLY PARALLEL per dimension (no cross-thread communication —
 * each of the 128 feature dims gets its own independent softmax over the pool's
 * `pool_size` members), so it needs no LDS. The Hadamard-128 rotation is the one part
 * that genuinely crosses lanes — 7 butterfly stages through LDS, `__syncthreads()`
 * between each. The absmax reduction reuses `block_max`.
 *
 * `d_dsa_pool_compress` (prefill mode) VERIFIED on gfx950 hardware (2026-09-01) against
 * `/home/shaswot/plow-work/kpool_oracle.npz` via `runtime/tests/dsa_pool_gfx950_test.hip`:
 * **0 mismatches, 256/256 output bytes bit-exact** — the fp8 quantization matches the
 * reference to the exact byte, not just within a rounding tolerance, including the
 * power-of-2 scale for both pools tested.
 *
 * `d_dsa_pool_stash` + `d_dsa_pool_compress`'s DECODE-MODE gate (op 125 / op 123 with
 * `t5=pos`) VERIFIED on gfx950 hardware (2026-09-01) against
 * `/home/shaswot/plow-work/decode_kpool_oracle.npz` (built by running vLLM's real
 * `_kpool_decode_update_batched_kernel` on this box's GPU) via
 * `runtime/tests/dsa_pool_decode_gfx950_test.hip`: 6 sequential decode steps
 * (pool_size=4), ring contents checked after every step and the boundary-compress output
 * checked at step 3 — **0 mismatches**, including the power-of-2 scale.
 *
 * **CORRECTION (2026-09-01), read before trusting the paragraph above for anything
 * beyond ONE boundary**: that single-boundary test could not distinguish "writes the
 * right pool slot" from "always writes slot 0" — a real bug that shipped in the write
 * path (fixed below in `pool_idx`/`wpool`, see `d_dsa_pool_compress`'s own doc comment).
 * Re-verified on gfx950 hardware, same day, against a SECOND, TWO-boundary oracle
 * (`/home/shaswot/plow-work/decode_kpool_oracle_multiboundary.npz`, 8 decode steps,
 * boundaries at step 3 -> pool0 and step 7 -> pool1) via
 * `runtime/tests/dsa_pool_decode_mb_gfx950_test.hip`, which re-checks EVERY
 * previously-written pool's bytes after every subsequent step (not just the latest
 * write) — **0 mismatches across both pools' final state**. Sanity-checked the test
 * itself has teeth by reverting the fix and re-running: it correctly failed with 254
 * mismatches, pool 0 shown corrupted by pool 1's write. Lesson: a "0 mismatches"
 * hardware result is only as strong as what the test's state space actually covers —
 * check that before trusting it, especially for anything indexed by a runtime-only
 * value like a growing decode-time cache slot.
 *
 * `d_dsa_pool_expand` (op 124) was fixed the same day: it took a materialized
 * `seq_lens[rows]` array, but nothing in the prefill DSA chain ever produces one — fixed
 * to compute each row's seq_len from a single scalar `kv_len` + the row index, mirroring
 * `d_index_select_pf`'s own derivation exactly. See `DevOp::DsaPoolExpand`'s doc comment
 * (`crates/packet/src/dev.rs`) for the exact formula. Re-verified on gfx950 hardware
 * (2026-09-01) via `runtime/tests/dsa_pool_gfx950_test.hip`'s `test_expand`/
 * `test_expand_decode`: **0 mismatches** across a 4-row causal-chunk case (all four
 * tail_count values 0-3 in one case) and the rows==1 decode-degenerate case. Teeth
 * proven: deliberately reintroduced the "every row uses the same kv_len[0]" bug,
 * rebuilt, got 6 real mismatches in the multi-row case (decode's rows==1 case stayed 0
 * mismatches, as expected — the bug is invisible in the single-row degenerate case,
 * exactly why it existed unnoticed) — then restored and reconfirmed 0.
 *
 * `d_dsa_pool_compress`'s DECODE-MODE fix above (`pool_idx = pos[0]/pool_size`) had a
 * PREFILL twin gap: prefill genuinely chunks a long context, and without an equivalent
 * chunk-base the pool cache would silently overwrite earlier chunks with later ones —
 * same failure class, one level up. Fixed (2026-09-01) with a `chunk_base` parameter,
 * host-patched per chunk via `crates/plowrt/src/exec/amd.rs`'s `kv_write_row_field`
 * (the SAME generic per-chunk row-rebase table `kv.{L}.ckv`/`kv.{L}.krot` already use —
 * one new match arm, not a new mechanism). See `d_dsa_pool_compress`'s own doc comment
 * for the exact formula.
 *
 * **CORRECTION (2026-09-01, caught on resume, not by the agent that wrote the fix)**: a
 * prior version of this comment claimed `runtime/tests/dsa_pool_prefill_chunk_gfx950_
 * test.hip` existed and had been hardware-verified at 0 mismatches. That test file did
 * NOT exist — the claim was written but the test was never created or run (the agent
 * doing this work was killed mid-task by a rate limit before reaching that step). The
 * test now genuinely exists (same file): a real two-chunk case into a SHARED, GROWING
 * 4-pool cache buffer — chunk 0 at chunk_base=0 (pool_idx=0, writes pools 0-1), chunk 1
 * at chunk_base=8 (pool_idx=2, writes pools 2-3), both chunks reusing the same
 * oracle-verified compress input so a correct kernel produces identical bytes at both
 * destinations. **Verified on gfx950 hardware (2026-09-01), independently re-run**:
 * **0 mismatches across all 4 pools.** Teeth proven the same way as every other fix in
 * this campaign: reverted `pool_idx` to always compute 0 for the prefill branch,
 * rebuilt, reran — chunk 1's pools showed the predicted "still poisoned" signature
 * (258 mismatches, scale still `-999`, the pre-write sentinel, meaning chunk 1's write
 * landed at pools 0-1 and never touched 2-3) — then restored the fix and reconfirmed
 * 0 mismatches. Full `cargo test -p devgen -p packet -p plowrt --lib` (252+60+135, only
 * pre-existing unrelated failures) and a full 49-object gfx950 rebuild both clean.
 *
 * **Getting this test to run at all uncovered a real, unrelated environment bug worth
 * recording** (not a plow code issue, but it silently broke EVERY `.hip` test on this
 * box, including previously-passing ones, so it belongs here): `sg render -c "..."`
 * (needed because group membership changes don't apply to an already-running shell)
 * execs through `newgrp`, which is setuid-root — that trips glibc's `AT_SECURE` mode in
 * the child process, which silently DROPS `LD_LIBRARY_PATH` (confirmed directly:
 * `LD_LIBRARY_PATH=/x sg render -c 'echo $LD_LIBRARY_PATH'` prints nothing). Every test
 * binary in this campaign was linked with `-L$ROCM_PATH/lib -lamdhip64` (or the
 * `/opt/rocm` equivalent) relying on `LD_LIBRARY_PATH` to find the right
 * `libamdhip64.so.7` at runtime — under `sg render` that env var never took effect, so
 * the binary silently fell back to whatever `libamdhip64.so.7` the system ld.so cache
 * found by default, whose bundled comgr then failed to link its own internal blit-copy
 * kernel bitcode ("undefined hidden symbol: __ockl_dm_init_v1" and several
 * `__amd_rocclr_*` symbols) — this reproduced on a minimal, plow-free
 * `hipMalloc`+`hipMemcpy` program with zero plow code involved. **Fix**: link with
 * `-Wl,-rpath,$ROCM_PATH/lib` instead of relying on `-L`/`LD_LIBRARY_PATH` at runtime —
 * RPATH is baked into the ELF, not an environment variable, so it survives
 * `AT_SECURE`. Every future `.hip` test's host-compile pass should add this flag; see
 * `status.md`'s verification section for the corrected command.
 */
#ifndef PLOW_OP_DSA_POOL_H
#define PLOW_OP_DSA_POOL_H

#include "amd_common.h"

/* One butterfly stage of the fixed 128-wide fast Walsh-Hadamard transform, ported
 * verbatim from the reference's `_hadamard128_stage` (itself ported from sglang):
 * `out[g*2S+r] = x[g*2S+r] + x[g*2S+S+r]`, `out[g*2S+S+r] = x[g*2S+r] - x[g*2S+S+r]`,
 * for every group `g` of the `groups` blocks of width `2*stride`. Standard radix-2
 * FWHT butterfly; NOT a novel derivation — verify against the reference if this is ever
 * touched. `lds` must be exactly 128 floats and is fully overwritten each call. */
__device__ __forceinline__ float dsa_hadamard128_stage(float x, unsigned lane, unsigned stride,
                                                        float* __restrict__ lds) {
    lds[lane] = x;
    __syncthreads();
    const unsigned block2s = 2u * stride;
    const unsigned base = (lane / block2s) * block2s;
    const unsigned rem = lane % block2s;
    const unsigned r = (rem < stride) ? rem : (rem - stride);
    const float a = lds[base + r];
    const float b = lds[base + stride + r];
    const float out = (rem < stride) ? (a + b) : (a - b);
    __syncthreads(); /* lds fully consumed before the next stage overwrites it */
    return out;
}

/* op 123 — per-pool softmax-weighted compress -> Hadamard-128 -> fp8 quant. See the file
 * header. `head_dim` is 128 for every shipped GLM-5.3-Flash shape; the 128-wide LDS
 * buffer and the fixed 7-stage transform assume it — the emitter must assert this.
 *
 * DECODE MODE (`pos != nullptr`, `n_pools` MUST be 1): decode re-emits the same packet
 * program every step, so "is this step a pool boundary" can only be decided at run time
 * by reading the LIVE device-side position, not by the host choosing whether to emit the
 * op. Every thread reads the same `pos[0]` from global memory and computes the same
 * boundary decision, so the early return is UNIFORM across the whole workgroup — safe
 * against the `__syncthreads()` calls inside the Hadamard stages below (a divergent
 * return here would deadlock them). `pos == nullptr` (the prefill call) skips the check
 * entirely: unconditional, byte-identical to the pre-decode-mode behavior.
 *
 * WRITE ADDRESS, BOTH MODES. `compressed_k`/`compressed_scale` point at the GROWING
 * per-layer pool cache, not a single-pool scratch buffer. In DECODE this is because the
 * host re-emits the identical packet every step and can never re-point these tensor
 * handles per step — the only thing that changes step to step is `pos[0]`, so the kernel
 * computes which pool slot (0, 1, 2, ...) this boundary crossing belongs to from `pos[0]`
 * itself: `pool_idx = pos[0] / pool_size` (integer division; at a boundary step
 * `pos[0]+1` is an exact multiple of `pool_size`, so e.g. pool_size=4, pos=3 ->
 * pool_idx=0 (tokens 0-3), pos=7 -> pool_idx=1 (tokens 4-7)). This mirrors
 * `d_headnorm_rope`'s `obase` (`op_norm.h`) — the established pattern in this codebase
 * for "decode-time write into a growing/positional cache."
 *
 * PREFILL has the IDENTICAL problem one level up: a long context is processed in
 * MULTIPLE CHUNKS (the same append discipline `kidx_pf`'s dense k-cache write already
 * has — `out_row0`, "patched per chunk by the host exactly as `ckv`/`krot` are",
 * `mla.rs`). Each chunk's own `n_pools` pools are correctly ordered 0..n_pools-1
 * WITHIN that chunk, but without a chunk base every chunk would write to the SAME cache
 * offsets, overwriting earlier chunks. `chunk_base` (TOKEN-granular, host-patched per
 * chunk via `crates/plowrt/src/exec/amd.rs`'s `kv_write_row_field` — the same generic
 * per-chunk row-rebase mechanism `kv.{L}.ckv`/`kv.{L}.krot` already use, extended with
 * one new match arm for this op) plays exactly `pos[0]`'s role: `pool_idx =
 * chunk_base / pool_size`. `pos` and `chunk_base` are mutually exclusive by construction
 * (decode passes `pos`, prefill passes `chunk_base`; whichever mode is active ignores
 * the other's field) — both reduce to "derive `pool_idx` from a token-granular scalar,"
 * unifying both modes' addressing instead of inventing two different mechanisms.
 *
 * A PRIOR VERSION OF THIS FUNCTION DID NOT DO EITHER: it always wrote to offset 0
 * regardless of `pos`/chunk, so every pool after the first (decode) or every chunk after
 * the first (prefill) silently overwrote pool 0. The decode half was fixed and
 * multi-boundary-verified 2026-09-01; the original hardware test for it crossed only ONE
 * boundary, which could not have caught the bug — a lesson directly applied to the
 * prefill fix's own verification (see the file header for both). */
__device__ void d_dsa_pool_compress(uint8_t* __restrict__ compressed_k,
                                    float* __restrict__ compressed_scale,
                                    const bf16* __restrict__ slot_k, const bf16* __restrict__ slot_score,
                                    const float* __restrict__ ape, unsigned n_pools, unsigned pool_size,
                                    unsigned head_dim, unsigned slice, unsigned nblk,
                                    float* __restrict__ lds, float* __restrict__ part,
                                    const int* __restrict__ pos = nullptr, unsigned chunk_base = 0u) {
    if (pos != nullptr && ((pos[0] + 1) % (int)pool_size) != 0) return;
    const unsigned pool_idx = (pos != nullptr) ? ((unsigned)pos[0] / pool_size) : (chunk_base / pool_size);

    const unsigned d = threadIdx.x;
    const bool active = d < head_dim;

    for (unsigned pool = slice; pool < n_pools; pool += nblk) {
        const unsigned wpool = pool + pool_idx; /* decode: pool==0, offset by pool_idx; prefill: pool_idx==0, unchanged */
        float x = 0.0f;
        if (active) {
            /* Per-dim softmax over the pool_size slots. Fully independent per thread —
             * no LDS, no cross-lane traffic. logits = gate score + additive position
             * bias, exactly the reference's two-pass (max, then weighted sum) shape,
             * collapsed to one pass since a single thread owns the whole reduction. */
            float maxs = -3.0e38f;
            for (unsigned s = 0; s < pool_size; s++) {
                const float sc = bf2f(slot_score[((size_t)pool * pool_size + s) * head_dim + d]) +
                                 ape[(size_t)s * head_dim + d];
                maxs = fmaxf(maxs, sc);
            }
            float denom = 0.0f, acc = 0.0f;
            for (unsigned s = 0; s < pool_size; s++) {
                const float sc = bf2f(slot_score[((size_t)pool * pool_size + s) * head_dim + d]) +
                                 ape[(size_t)s * head_dim + d];
                const float p = expf(sc - maxs);
                denom += p;
                acc += bf2f(slot_k[((size_t)pool * pool_size + s) * head_dim + d]) * p;
            }
            /* bf16 round-trip #1 — matches the reference's `.to(bf16).to(f32)`, so the
             * fp8 quant that follows sees the same precision as the unfused path. */
            x = bf2f(f2bf(acc / denom));
        }

        /* Hadamard-128: 7 stages, stride doubling 1,2,4,...,64. Inactive lanes (only
         * possible if head_dim < 128, which no shipped shape does) carry 0 through
         * harmlessly — the transform is fixed-width regardless. */
#pragma unroll
        for (unsigned stage = 0, stride = 1; stage < 7; stage++, stride <<= 1)
            x = dsa_hadamard128_stage(x, d, stride, lds);
        x *= 0.08838834764831845f; /* 1/sqrt(128), the reference's own normalization */
        x = bf2f(f2bf(x));         /* bf16 round-trip #2, post-Hadamard */

        /* Per-vector absmax, POWER-OF-2 ROUNDED scale (`ROUND_SCALE=True` in the
         * reference) — NOT plain absmax. Getting this the "obvious" way (plain absmax)
         * is a silent, plausible, wrong compressed cache. */
        const float ax = active ? fabsf(x) : 0.0f;
        const float absmax = fmaxf(block_max(ax, part), 1e-4f);
        const float scale = exp2f(ceilf(log2f(absmax / PLOW_FP8_E4M3_MAX)));

        if (active) {
            /* wpool, NOT pool: the growing-cache slot (see the DECODE-MODE WRITE ADDRESS
             * note above). slot_k/slot_score above deliberately keep using `pool` — those
             * index the staging window (the decode ring, or a prefill chunk's local
             * pools), not the output cache, and are unaffected by pool_idx. */
            compressed_k[(size_t)wpool * head_dim + d] = quant_fp8(x / scale);
            if (d == 0) compressed_scale[wpool] = scale;
        }
    }
}

/* op 124 — pool-select expand + tail-append, fused. Pure index arithmetic (no floats
 * anywhere), one thread per output element, grid-strided — no reduction, no LDS. Mirrors
 * `expand_pools_to_tokens` + `append_tail_to_topk`'s identity-path composition exactly
 * (the reference's own fused kernel does the same fusion, for the same reason: the two
 * separate calls are otherwise the only path GLM5-Next's indexer exercises).
 *
 * PER-ROW seq_len IS COMPUTED, NOT READ FROM AN ARRAY — a prior version of this function
 * took a materialized `seq_lens[rows]` tensor, but nothing in the prefill DSA chain ever
 * produces one: `d_index_select_pf` (op 118), which feeds this op's `pool_ids`, derives
 * the identical per-row token count from a single SCALAR chunk-end `kv_len` plus the row
 * index (`q_pos0 = kv_len[0] - n_tok; row_len = q_pos0 + t + 1`) — no array anywhere.
 * This function now mirrors that exact formula: `kv_len` is the scalar end-of-chunk
 * token count (row `rows-1`, the LAST/most-recent row, has `seq_len == kv_len[0]`; each
 * earlier row has one fewer token, the same causal geometry `d_index_select_pf` assumes).
 * DECODE (`rows == 1`) is the degenerate case and needs no special handling: `q_pos0 =
 * kv_len[0] - 1`, `seq_len = q_pos0 + 0 + 1 = kv_len[0]` — exactly what the OLD
 * materialized-array contract already gave decode (`seq_lens[0] == kv_len[0]` in
 * practice, since decode's occupancy tensor IS the one row's own seq_len), so the
 * decode-mode call site's `n.kvlen` tensor plugs into this new scalar parameter
 * unchanged — same tensor, reinterpreted contract, verified byte-identical. */
__device__ void d_dsa_pool_expand(int32_t* __restrict__ out, const int32_t* __restrict__ pool_ids,
                                  const int32_t* __restrict__ kv_len, unsigned rows,
                                  unsigned n_groups, unsigned pool_size, unsigned slice, unsigned nblk) {
    const unsigned topk = n_groups * pool_size;
    const unsigned out_cols = topk + pool_size - 1;
    const unsigned total = rows * out_cols;
    const int q_pos0 = (int)kv_len[0] - (int)rows;
    for (unsigned idx = slice * PLOW_THREADS + threadIdx.x; idx < total; idx += nblk * PLOW_THREADS) {
        const unsigned row = idx / out_cols;
        const unsigned col = idx % out_cols;
        const int seq_len = q_pos0 + (int)row + 1;
        const int pool_len = seq_len / (int)pool_size;
        const int tail_start = pool_len * (int)pool_size;
        const int tail_count = seq_len - tail_start;
        int result;
        if (col < topk) {
            const unsigned g = col / pool_size;
            const unsigned o = col % pool_size;
            const int pid = pool_ids[(size_t)row * n_groups + g];
            result = (pid >= 0) ? (pid * (int)pool_size + (int)o) : -1;
        } else {
            const int tail_off = (int)col - (int)topk;
            result = (tail_off < tail_count) ? (tail_start + tail_off) : -1;
        }
        out[idx] = result;
    }
}

/* op 125 — decode-side ring stash. Unconditional, every decode step: write this step's
 * roped indexer key + projected gate score into a small per-layer ring of `pool_size`
 * slots at `pos % pool_size`, so [`d_dsa_pool_compress`]'s decode-mode gate has a
 * complete, slot-ordered pool to read once every `pool_size` steps. One thread per
 * feature dim, no reduction, no LDS. Verified against `decode_kpool_oracle.npz`
 * alongside `d_dsa_pool_compress`'s decode-mode gate (same hardware test). */
__device__ void d_dsa_pool_stash(bf16* __restrict__ ring_k, bf16* __restrict__ ring_score,
                                 const bf16* __restrict__ cur_k, const bf16* __restrict__ cur_score,
                                 const int* __restrict__ pos, unsigned pool_size, unsigned head_dim,
                                 unsigned row = 0u) {
    const unsigned d = threadIdx.x;
    if (d >= head_dim) return;
    const unsigned slot = (unsigned)pos[row] % pool_size;
    ring_k[(size_t)slot * head_dim + d] = cur_k[(size_t)row * head_dim + d];
    ring_score[(size_t)slot * head_dim + d] = cur_score[(size_t)row * head_dim + d];
}

/* op 126 — indexer QUERY-side fp8 quant, one indexer head's `head_dim`-wide vector per
 * "row" (row = one (token, index_head) pair, flattened by the caller — `q_raw` is
 * `[n_rows][head_dim]`). Ported from vLLM's real `fwht128_quant_fp8`/`_fwht_quant_kernel`
 * (`kpool_compress.py`), verified against a numerical oracle GENERATED BY RUNNING THAT
 * REAL FUNCTION on this box's GPU (see `crates/packet/src/dev.rs`'s doc comment for the
 * campaign notes). Strict SUBSET of [`d_dsa_pool_compress`]'s math — same Hadamard-128
 * rotation (same `dsa_hadamard128_stage`, same `1/sqrt(128)` constant), same power-of-2
 * ROUNDED fp8 scale (`exp2(ceil(log2(absmax/448)))`, same 1e-4 absmax floor) — but ONE
 * bf16 round-trip instead of two (there is no softmax-pooling step on the query side,
 * so there is no "pre-Hadamard" round-trip to begin with) and no pooling loop at all:
 * one row in, one row out, no `pool_size`. */
__device__ void d_dsa_q_quant(uint8_t* __restrict__ q_fp8, float* __restrict__ q_scale,
                              const bf16* __restrict__ q_raw, unsigned n_rows, unsigned head_dim,
                              unsigned slice, unsigned nblk, float* __restrict__ lds,
                              float* __restrict__ part) {
    const unsigned d = threadIdx.x;
    const bool active = d < head_dim;

    for (unsigned row = slice; row < n_rows; row += nblk) {
        float x = active ? bf2f(q_raw[(size_t)row * head_dim + d]) : 0.0f;

#pragma unroll
        for (unsigned stage = 0, stride = 1; stage < 7; stage++, stride <<= 1)
            x = dsa_hadamard128_stage(x, d, stride, lds);
        x *= 0.08838834764831845f; /* 1/sqrt(128) */
        x = bf2f(f2bf(x));         /* the query side's ONE bf16 round-trip (post-Hadamard) */

        const float ax = active ? fabsf(x) : 0.0f;
        const float absmax = fmaxf(block_max(ax, part), 1e-4f);
        const float scale = exp2f(ceilf(log2f(absmax / PLOW_FP8_E4M3_MAX)));

        if (active) {
            q_fp8[(size_t)row * head_dim + d] = quant_fp8(x / scale);
            if (d == 0) q_scale[row] = scale;
        }
    }
}

#endif /* PLOW_OP_DSA_POOL_H */
