//! Compile all three Gemma 4 model variants (12B dense, 31B dense, 26B MoE)
//! end-to-end on the MI350X with a production bucket ladder and all optimization
//! passes enabled. Validates:
//!
//! - Every bucket compiles to a non-empty packet stream
//! - Tile shapes exploit the 160 KiB LDS (BN >= 64 on prefill GEMMs)
//! - All output assets are produced
//! - Lean verification passes (when feature is available)
//!
//! This test exercises the "proper heuristics" path: CDNA4-aware tile selection
//! via the widened BN candidates in `costmodel::tile`, egglog argmin over the
//! expanded candidate set, and SRAM-fit promotion leveraging the 10-page budget
//! (160 KiB / 16 KiB pages).

use plowc::{compile, net::NetConfig, Options, Parallel, Source};
use schedule::Phase;
use std::path::PathBuf;

fn examples_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("examples")
}

/// The Gemma family: all three model-variant JSONs in the examples directory.
fn gemma_examples() -> Vec<(&'static str, PathBuf)> {
    let dir = examples_dir();
    vec![
        ("gemma4-12b", dir.join("transformer_block_gemma4_12b.json")),
        ("gemma4-31b", dir.join("transformer_block_gemma4_31b.json")),
        ("gemma4-26b-moe", dir.join("moe_gemma4_26b_a4b.json")),
    ]
}

/// CI-friendly bucket ladder: smaller than production (which uses batch 1/8/32
/// × seq 1/128/512/2048/8192). The full ladder is meant for the MI350X box and
/// is generated by `scripts/compile_gemma_family.sh`.
fn mi350x_opts(out: PathBuf) -> Options {
    Options {
        no_tuning: false,
        tuning_db: None,
        gpu: "MI350X".into(),
        num_gpus: 1,
        parallel: Parallel::Tp,
        batches: vec![1],
        seqs: vec![1, 128],
        phases: vec![Phase::Decode, Phase::Prefill],
        page_kib: 16,
        out,
        lean_verify: cfg!(feature = "lean-verify"),
        counter_elim: true,
        scope_narrow: true,
        prefetch: true,
        sram_fit: true,
        lean_oracle: false,
        emit_sample: true,
        emit_tokenize: true,
        emit_trace: false, // skip trace to keep test fast
        kv: Default::default(),
        weight_dtype_override: None,
    }
}

/// CI bucket count: 2 phases × 1 batch × 2 seqs = 4 buckets per model.
const EXPECTED_BUCKETS: usize = 2 * 1 * 2; // 4

/// Is there a `plow_verify` here? cfg-split because the crate is only a
/// dependency when the feature is on.
#[cfg(feature = "lean-verify")]
fn verifier_present() -> bool {
    lean_verify::binary_available()
}
#[cfg(not(feature = "lean-verify"))]
fn verifier_present() -> bool {
    false
}

#[test]
fn gemma_family_compiles_on_mi350x() {
    for (name, path) in gemma_examples() {
        let json =
            std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{name}: read failed: {e}"));
        let net: NetConfig =
            serde_json::from_str(&json).unwrap_or_else(|e| panic!("{name}: parse failed: {e}"));

        let out = std::env::temp_dir().join(format!(
            "plowc-gemma-mi350x-{}-{}",
            name,
            std::process::id()
        ));
        let report = compile(&Source::Net(net), &mi350x_opts(out.clone()))
            .unwrap_or_else(|e| panic!("{name}: compile failed: {e}"));

        // THE COMPILE SURVIVED A MISSING VERIFIER — and said so.
        //
        // `lean-verify` is in plowc's default feature set now, so this compile
        // asks for the gate on every one of its buckets. On a box with no
        // `plow_verify` it must warn, skip, and finish; before the degrade
        // landed this exact test died with "spawn failed: No such file or
        // directory" on bucket `decode_b1_s1`.
        //
        // And the skip must be VISIBLE. A gate that quietly does nothing is
        // worth less than no gate, because it reads as a pass.
        if cfg!(feature = "lean-verify") && !verifier_present() {
            assert!(
                !report.lean_verified,
                "{name}: no plow_verify on this box, yet the report claims verification"
            );
            assert!(
                !report.lean_provenance.is_empty(),
                "{name}: lean_verified=false with no provenance is the `tier: portable` bug again"
            );
        }

        // All buckets compiled.
        assert_eq!(
            report.buckets.len(),
            EXPECTED_BUCKETS,
            "{name}: expected {EXPECTED_BUCKETS} buckets, got {}",
            report.buckets.len()
        );

        // Every bucket has a non-empty packet stream and positive makespan.
        for b in &report.buckets {
            assert!(
                b.packet_bytes > 0,
                "{name}/{}: empty packet stream",
                b.packet_file
            );
            assert!(
                b.instructions > 0,
                "{name}/{}: no instructions",
                b.packet_file
            );
            assert!(b.makespan > 0, "{name}/{}: zero makespan", b.packet_file);
        }

        // Weight layout unification across buckets: expected for dense models,
        // but MoE models have incompatible GEMM shapes (router n=8 vs expert
        // n=16384) that prevent a single (BN, BK) from covering all ops.
        if !name.contains("moe") {
            assert!(
                report.weight_shared,
                "{name}: weight not shared across buckets"
            );
        }

        // Assets file was produced.
        let assets = report.assets.as_ref().expect("assets summary");
        assert!(assets.regions.total_hbm_peak > 0, "{name}: zero HBM peak");
        // MI350X has 288 GiB — ensure we don't exceed it.
        let hbm_288g: u64 = 288 * 1024 * 1024 * 1024;
        assert!(
            assets.regions.total_hbm_peak < hbm_288g,
            "{name}: HBM peak {} exceeds MI350X capacity {}",
            assets.regions.total_hbm_peak,
            hbm_288g
        );

        // On-disk assets are non-trivial.
        assert!(
            assets.on_disk.packets_total > 0,
            "{name}: no packet files on disk"
        );
        assert!(
            assets.on_disk.map_json_total > 0,
            "{name}: no map files on disk"
        );

        // Verify output directory has expected files.
        assert!(
            out.join("weights.json").exists(),
            "{name}: missing weights.json"
        );
        assert!(
            out.join("assets.json").exists(),
            "{name}: missing assets.json"
        );
        assert!(
            out.join("footprint.json").exists(),
            "{name}: missing footprint.json"
        );
        assert!(
            out.join("footprint.csv").exists(),
            "{name}: missing footprint.csv"
        );

        // Clean up.
        std::fs::remove_dir_all(&out).ok();
    }
}

/// Verify that prefill buckets on MI350X choose wide BN tiles (>= 64),
/// proving the CDNA4 heuristic override in `costmodel::tile` is effective.
#[test]
fn mi350x_prefill_uses_wide_tiles() {
    let path = examples_dir().join("transformer_block_gemma4_12b.json");
    let json = std::fs::read_to_string(&path).expect("read");
    let net: NetConfig = serde_json::from_str(&json).expect("parse");

    // Single large prefill bucket to inspect tile choices.
    let out = std::env::temp_dir().join(format!("plowc-tile-check-{}", std::process::id()));
    let opts = Options {
        no_tuning: false,
        tuning_db: None,
        gpu: "MI350X".into(),
        num_gpus: 1,
        parallel: Parallel::Tp,
        batches: vec![1],
        seqs: vec![1024],
        phases: vec![Phase::Prefill],
        page_kib: 16,
        out: out.clone(),
        lean_verify: false,
        counter_elim: false,
        scope_narrow: false,
        prefetch: false,
        sram_fit: false,
        lean_oracle: false,
        emit_sample: false,
        emit_tokenize: false,
        emit_trace: false,
        kv: Default::default(),
        weight_dtype_override: None,
    };

    let report = compile(&Source::Net(net), &opts).expect("compile");
    assert_eq!(report.buckets.len(), 1);

    // The bucket should have tile_nodes > 0 (GEMMs were tiled).
    let b = &report.buckets[0];
    assert!(b.tile_nodes > 0, "no tile nodes in prefill bucket");

    // With BN >= 64 and a hidden of 3072, we should get reasonable tile counts.
    // A BN=32 tiling of N=3072 would give 96 tiles per row; BN=64 gives 48.
    // With wide tiles the task count should be meaningfully lower than with
    // BN=32 (fewer, larger tiles).
    assert!(b.tasks > 0, "zero tasks — tiling produced nothing");

    std::fs::remove_dir_all(&out).ok();
}

/// Verify the SRAM page budget on MI350X is 10 pages (160 KiB / 16 KiB).
/// This confirms the Lean checkpoint C budget would be correct.
#[test]
fn mi350x_sram_budget_is_10_pages() {
    use costmodel::sram::SramModel;
    let spec = costmodel::hwspec::registry::lookup("MI350X").expect("MI350X spec");
    let model = SramModel::from_spec(spec, 16 * 1024); // page_kib = 16
    assert_eq!(
        model.pages_per_sm, 10,
        "MI350X at 16 KiB pages should have 10 SRAM pages, got {}",
        model.pages_per_sm
    );
}
