#!/usr/bin/env python3
# qos0 <cmd...>: run cmd while holding /dev/cpu_dma_latency at 0 us (no deep C-states).
import os, struct, subprocess, sys
fd = os.open("/dev/cpu_dma_latency", os.O_WRONLY)
os.write(fd, struct.pack("i", 0))
sys.exit(subprocess.call(sys.argv[1:]))
