#!/usr/bin/env bash
# Self-test for build_gfx942.sh's PLOW_HSACO_CONFIG path, in PLOW_DEFINES_ONLY mode (no hipcc
# compile, seconds). Asserts, against a synthetic plow_config.h shaped like the one
# devgen::manifest::config_header writes:
#   * every row is stamped (-DPLOW_CONFIG="plow_config.h" in build_defines.json);
#   * the decode batch, walk, tiers, packed rows and opt-in arms are DERIVED from the packet;
#   * an environment that disagrees with the packet by name is refused, not built;
#   * without PLOW_HSACO_CONFIG the recorded -D set mentions no config at all.
# Runs inside `nix develop` (build_gfx942.sh insists on the flake's toolchain).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ -n "${IN_NIX_SHELL:-}" ] || { echo "build_gfx942 config selftest: SKIP (not in nix develop)"; exit 0; }
TMP="$(mktemp -d /tmp/plow-gfx942-config-selftest.XXXXXX)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/assets"

cat >"$TMP/assets/plow_config.h" <<'H'
/* GENERATED by devgen::manifest — do not edit. (selftest fixture) */
#pragma once

#define PLOW_PACKET_HASH 0x78432b9701fed7acull

/* --- packet and per-object opcode inventory --- */
#define PLOW_PACKET_HAS_DECODE_MLA_SEGMENTS 0
#define PLOW_PACKET_HAS_PACKED_PREFILL_TOPOLOGY 1
#define PLOW_PACKET_HAS_TOKEN_BATCH_BODIES 1

/* --- rule-derived shape constants --- */
#ifndef GV_MM_MAX
#define GV_MM_MAX 32
#endif

/* --- object recipe inputs (scripts/build_gfx942.sh PLOW_HSACO_CONFIG) --- */
#define PLOW_PACKET_OBJECT_ARCH "gfx942"
#define PLOW_PACKET_OBJECT_REQUIRES "PLOW_WG_WAVES=8 GM_DBUF=1 GM_BM=192 GM_BN=256 PLOW_BUCKET_DECODE=0 PLOW_FP8=1 PLOW_FP8_KV=1 PLOW_MLA_PREFILL=1 PLOW_MOE_PREFILL=1 PLOW_MOE_PF_PART16=1 PLOW_MOE_PF_ATOMIC=1 PLOW_KDA_CHUNK=1 PLOW_DSA_PF_ARM=1"
#define PLOW_PACKET_DECODE_BATCH 20
#define PLOW_PACKET_DECODE_LADDER "1,2,4,8,16,20"
H

fail=0
say() { echo "  $*"; }
expect() {  # <desc> <cond...>
  local d="$1"; shift
  if "$@"; then say "ok    $d"; else say "FAIL  $d"; fail=1; fi
}
has_define() {  # <defines.json> <stem> <token>
  python3 - "$@" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
sys.exit(0 if sys.argv[2] in d and sys.argv[3] in d[sys.argv[2]].split() else 1)
PY
}

echo "--- config build (defines only)"
env -u PLOW_DECODE_BATCH -u PLOW_GEMV_WALK -u PLOW_DECODE_TIERS -u PLOW_DSA_PF -u PLOW_KDA_CHUNK \
    -u PLOW_MOE_PF_ATOMIC -u PLOW_PACKED_PREFILL_CONSUMERS -u PLOW_TOKEN_BATCH_TP_OBJECTS \
    -u GM_BM -u GM_BN -u GM_DBUF \
    PLOW_HSACO_CONFIG="$TMP/assets" PLOW_DEFINES_ONLY=1 \
    "$ROOT/scripts/build_gfx942.sh" "$TMP/cfg" >"$TMP/cfg.log" 2>&1 || { cat "$TMP/cfg.log"; exit 1; }
D="$TMP/cfg/build_defines.json"
expect "summary derives batch/walk/tiers/packed/arms from the packet" \
  grep -q "packet config: hash=0x78432b9701fed7ac batch=20 walk=1 tiers=1,2,4,8,16 packed=1 tb=1 dsa_pf=1 moe_pf_atomic=1 moe_pf_det=1 kda_chunk=1" "$TMP/cfg.log"
expect "unmapped requires are named, not dropped" \
  grep -q "requires with no build knob here (marker-checked at load): PLOW_MOE_PF_PART16=1" "$TMP/cfg.log"
expect "every row is stamped with the config" python3 - "$D" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
bad = [k for k, v in d.items() if k != "test_kernels" and '-DPLOW_CONFIG="plow_config.h"' not in v.split()]
sys.exit(1 if bad else 0)
PY
expect "decode bucket is the walk-capped ceiling of the packet batch" has_define "$D" interp_decode -DPLOW_GEMV_MM=16
expect "decode walks above 16 rows" has_define "$D" interp_decode -DPLOW_GEMV_WALK=1
expect "decode compiles the grouped MoE seam at batch>1" has_define "$D" interp_decode -DPLOW_MOE_PREFILL=1
expect "flash row carries the DSA gathered arm the packet requires" has_define "$D" interp_flash -DPLOW_DSA_PF_ARM=1
expect "prefill row carries the fused-MoE arm the packet requires" has_define "$D" interp_prefill -DPLOW_MOE_PF_ATOMIC=1
expect "K3 prefill row carries the chunk-KDA arm the packet requires" has_define "$D" interp_prefill_k3 -DPLOW_KDA_CHUNK=1
expect "packed family rows are built for a packed-topology packet" python3 - "$D" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
sys.exit(0 if all(k in d for k in ("interp_packed_mla_norm", "interp_packed_mla_flash", "interp_packed_kda")) else 1)
PY
expect "token-batch _tb twins are built for a packet with body programs" python3 - "$D" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
tb = ("interp_packed_mla_norm_tb", "interp_packed_mla_flash_tb", "interp_packed_mla_norm_tb_fp8kv", "interp_packed_mla_flash_tb_fp8kv")
sys.exit(0 if all(k in d and "-DPLOW_PACKED_PREFILL_BAND=1" in d[k].split() for k in tb) else 1)
PY
expect "small-rung MLA and split rows are in every build" python3 - "$D" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
sys.exit(0 if all(k in d for k in ("interp_mla_small", "interp_mla_small_fp8kv", "interp_mla_split_fp8kv")) else 1)
PY

echo "--- explicit env still wins where it agrees or widens"
env -u PLOW_DECODE_TIERS PLOW_DECODE_BATCH=32 PLOW_GEMV_MM=16 PLOW_GEMV_WALK=1 PLOW_DSA_PF=0 \
    PLOW_HSACO_CONFIG="$TMP/assets/plow_config.h" PLOW_DEFINES_ONLY=1 \
    "$ROOT/scripts/build_gfx942.sh" "$TMP/wide" >"$TMP/wide.log" 2>&1 || { cat "$TMP/wide.log"; exit 1; }
expect "a wider explicit batch is kept, and every ladder rung below it becomes a tier" grep -q "batch=32 walk=1 tiers=1,2,4,8,16,20 " "$TMP/wide.log"
expect "an explicit opt-out is kept (PLOW_DSA_PF=0)" grep -q "dsa_pf=0" "$TMP/wide.log"

echo "--- refusals by name"
refuse() {  # <desc> <needle> <env...>
  local d="$1" needle="$2"; shift 2
  if env "$@" PLOW_HSACO_CONFIG="$TMP/assets" PLOW_DEFINES_ONLY=1 \
       "$ROOT/scripts/build_gfx942.sh" "$TMP/refuse" >"$TMP/refuse.log" 2>&1; then
    say "FAIL  $d (accepted)"; fail=1
  elif grep -q "$needle" "$TMP/refuse.log"; then
    say "ok    $d"
  else
    say "FAIL  $d (refused for another reason)"; cat "$TMP/refuse.log"; fail=1
  fi
}
refuse "narrower explicit decode batch" "packet decodes at batch 20 but PLOW_DECODE_BATCH=4" PLOW_DECODE_BATCH=4 PLOW_GEMV_WALK=1
refuse "disagreeing GEMM tile" "packet requires GM_BM=192 but GM_BM=64" GM_BM=64
sed -i 's/"gfx942"/"gfx950"/' "$TMP/assets/plow_config.h"
refuse "config for another arch" "describes a gfx950 packet" JOBS=1
sed -i 's/"gfx950"/"gfx942"/' "$TMP/assets/plow_config.h"
if PLOW_HSACO_CONFIG="$TMP/nowhere" PLOW_DEFINES_ONLY=1 "$ROOT/scripts/build_gfx942.sh" "$TMP/refuse" >"$TMP/refuse.log" 2>&1; then
  say "FAIL  missing config accepted"; fail=1
else
  expect "missing config refused" grep -q "no plow_config.h there" "$TMP/refuse.log"
fi

echo "--- no config: nothing changes"
env -u PLOW_HSACO_CONFIG -u PLOW_DECODE_BATCH -u PLOW_GEMV_WALK -u PLOW_DECODE_TIERS -u PLOW_DSA_PF \
    -u PLOW_PACKED_PREFILL_CONSUMERS -u PLOW_TOKEN_BATCH_TP_OBJECTS PLOW_DEFINES_ONLY=1 \
    "$ROOT/scripts/build_gfx942.sh" "$TMP/plain" >"$TMP/plain.log" 2>&1 || { cat "$TMP/plain.log"; exit 1; }
expect "no PLOW_CONFIG on any row" bash -c '! grep -q PLOW_CONFIG "$1"' _ "$TMP/plain/build_defines.json"
expect "no packet summary line" bash -c '! grep -q "packet config" "$1"' _ "$TMP/plain.log"
expect "B=1 decode bucket" has_define "$TMP/plain/build_defines.json" interp_decode -DPLOW_GEMV_MM=1
expect "no packed rows by default" python3 - "$TMP/plain/build_defines.json" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
sys.exit(1 if "interp_packed_mla_norm" in d or "interp_packed_mla_norm_tb" in d else 0)
PY

[ "$fail" = 0 ] || { echo "build_gfx942 config selftest: FAIL"; exit 1; }
echo "build_gfx942 config selftest: PASS"
