#!/usr/bin/env bash
# RE-RUN THE WHOLE gfx950 PREFILL-GEMM TILE CAMPAIGN — bf16 AND mxfp4 — AND PUBLISH IT.
#
# This refreshes the dense-GEMM family key. Relevant GEMM bodies, their expanded macros, and the
# toolchain participate; unrelated persistent-interpreter arms do not. `cargo test -p devgen
# --test tuned_tile_selection` is the signal. THIS SCRIPT IS THE FIX:
#
#     scripts/rebench_tune_gemm_all.sh                 # rebuild objects, measure both ladders, publish
#     scripts/rebench_tune_gemm_all.sh --bf16-only     # just the un-staling half (the test gate)
#     scripts/rebench_tune_gemm_all.sh --k3-only       # just the K3 bf16-vs-mxfp4 comparison
#
# It is deliberately ONE COMMAND end to end (rebuild -> measure -> ingest -> verify), because the
# 2026-07-29 failure was a campaign that measured 180 rows and published none while both halves
# reported success at their own boundary. `plowc tune gemm` always ingests; this wraps it.
#
# ------------------------------------------------------------------------------------------------
# THE TWO ENVIRONMENT RULES, AND THEY ARE OPPOSITES. Both are load-bearing.
#
#   * Build and measure with the SAME nix ROCm toolchain. The TuneDB key records that toolchain and
#     the preprocessed dense-GEMM family digest, so building test_kernels.elf with host ROCm and then
#     publishing through nix labels measurements with the wrong compiler. `sg render -c` still MUST
#     stay OUTSIDE `nix develop`: nix runs in a user namespace where /usr/bin/newgrp cannot acquire
#     the render gid. The command under `sg` enters nix for the measurement itself.
#   * `ROCR_VISIBLE_DEVICES`, NOT `HIP_VISIBLE_DEVICES`. `plowc tune gemm` forwards the former by
#     name and deliberately drops the latter: they COMPOSE, so setting both makes a correctly
#     targeted card report "no ROCm-capable device is detected".
#
# AND ROCR's DEVICE NUMBERING IS NOT rocm-smi's. ROCR enumerates agents in KFD NODE order; rocm-smi
# indexes by its own table. On this box, measured 2026-07-29:
#
#     ROCR 0 1 2 3 4 5 6 7   ->   rocm-smi dev 3 0 2 1 7 4 6 5
#
# So `ROCR_VISIBLE_DEVICES=5` is rocm-smi's device 4. VERIFY IT, do not assume it — the mapping is
# a property of the machine, not of this script. Run `rocm-smi` during the first shape and confirm
# the card you meant is the one at 100%. A benchmark on a contended GPU is worthless.
# ------------------------------------------------------------------------------------------------
#
# WHAT IT MEASURES, and why the shape lists come from two different places:
#
#   bf16 (`--shapes scripts/tune_shapes_bf16.txt`)
#       The 50-shape GLM-5.2 + Gemma + Qwen + Kimi list `scripts/rebench_tune_gemm.sh` carries.
#       32 of those 50 were DERIVED from GLM's demand with `--shapes auto`; the trailing 18 are the
#       original hand-authored set, kept verbatim so this campaign stays comparable to the one it
#       replaces. These are the records `tuned_tile_selection` reads.
#
#   K3 (`--shapes scripts/tune_shapes_k3.txt`, BOTH encodings at every shape)
#       Kimi-K3's real projection shapes at TP8, generated by `scripts/k3_shapes.py` FROM THE
#       CONFIG rather than typed out. `--shapes auto` CANNOT derive these: `kimi_k3_emit` is an
#       analysis-and-refusal path, not an emitter -- it panics with "full-model emit for a hybrid
#       MLA arch: THE ONE REMAINING BLOCKER" before reaching a single `pick_tile`, so there is no
#       demand log to read. When that blocker closes, DELETE the generated file and switch this to
#       `--shapes auto`; the generator's header says the same thing.
#
#       Both encodings at every shape ON PURPOSE. That is what makes "mxfp4 vs bf16 at this shape"
#       answerable at all, and the answer is not uniform -- see the campaign report.
set -euo pipefail

WT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OBJ="${PLOW_TUNE_OBJ:-/tmp/tunecamp-objs}"
OUT="${PLOW_TUNE_OUT:-/tmp/tunecamp}"
# rocm-smi device 4 by default; see the numbering note above.
ROCR="${ROCR_VISIBLE_DEVICES:-5}"
K3_CONFIG="${PLOW_K3_CONFIG:-/tmp/k3-synth}"
DO_BF16=1
DO_K3=1
case "${1:-}" in
  --bf16-only) DO_K3=0 ;;
  --k3-only)   DO_BF16=0 ;;
  "")          ;;
  *) echo "usage: $0 [--bf16-only|--k3-only]" >&2; exit 2 ;;
esac

mkdir -p "$OUT"
cd "$WT"

echo "=== 1/4  building the interpreter objects and test_kernels.elf into $OBJ"
# The object compiler must match `plowc tune`'s toolchain fingerprint. build_gfx950.sh uses
# PLOW_HOST_CC inside the dev shell, so its host harness and ROCm runtime remain a coherent pair.
nix develop --command ./scripts/build_gfx950.sh "$OBJ"

echo
echo "=== 2/4  building plowc"
nix develop --command cargo build --release -p plowc

echo
echo "=== 3/4  regenerating the K3 shape list from the config"
python3 ./scripts/k3_shapes.py "$K3_CONFIG" > "$WT/scripts/tune_shapes_k3.txt"
wc -l "$WT/scripts/tune_shapes_k3.txt"

echo
echo "=== 4/4  measuring and publishing (ROCR_VISIBLE_DEVICES=$ROCR)"
# One `sg render` for the whole campaign: the gid has to be acquired before nix starts, and
# re-acquiring it per shape would fork a shell per measurement for no gain.
cat > "$OUT/campaign.sh" <<INNER
#!/bin/bash
set -euo pipefail
cd "$WT"
export ROCR_VISIBLE_DEVICES=$ROCR
unset HIP_VISIBLE_DEVICES CUDA_VISIBLE_DEVICES
P="nix develop --command ./target/release/plowc"
if [ $DO_BF16 = 1 ]; then
  \$P tune gemm --gpu mi350 --root . --obj "$OBJ" \\
      --shapes scripts/tune_shapes_bf16.txt \\
      --samples "$OUT/bf16.jsonl" --campaign gemm-tile-inventory
fi
if [ $DO_K3 = 1 ]; then
  \$P tune gemm --gpu mi350 --root . --obj "$OBJ" \\
      --shapes scripts/tune_shapes_k3.txt \\
      --samples "$OUT/k3.jsonl" --campaign k3-mxfp4-tile-ladder
fi
INNER
chmod +x "$OUT/campaign.sh"
sg render -c "$OUT/campaign.sh"

echo
echo "=== verify"
nix develop --command ./target/release/plowc tune status --gpu mi350 --root .
# No `| head`: plowc panics on the broken pipe (Rust's stdout has no SIGPIPE handler) and would
# fail this script for a reason that is not a campaign failure. Count instead.
echo "mxfp4 op cases now selectable: $(nix develop --command ./target/release/plowc \
    tune best --gpu mi350 --root . --quant Mxfp4 | grep -c 'gemm/')"
nix develop --command cargo test -p devgen --test tuned_tile_selection
