"""attn_pf_hd256_sliding: causal sliding-window flash prefill, head_dim 256, bf16, sm_90a.

  attn_pf_hd256_sliding.py build OUT.cubin [--config k=v,...]   no GPU: nvcc one config
  attn_pf_hd256_sliding.py check CUBIN                           GPU: contract + rel-L2 suite
  attn_pf_hd256_sliding.py bench CUBIN [--role14 CUBIN] [--fa3]  GPU: us per shape class
  attn_pf_hd256_sliding.py tune OUT.json                         GPU: sweep configs per class

The kernel is runtime/nvidia/gen_attn_pf_hd256_sliding.cu, a parameterized wgmma template
(GEN_BN score tile, GEN_STAGES K/V ring depth, GEN_PREG/GEN_CREG producer/consumer register
split). Signature: head_dim 256, causal, any sliding window (0 = none), even GQA ratio, bf16
Q/K/V, ring or linear KV, packed requests. Shape classes are keyed by (heads, kv heads, window,
rows), never by model. Every GPU command runs under gpulease.
"""
import argparse, ctypes, itertools, json, math, os, re, struct, subprocess, sys, tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "runtime/nvidia/gen_attn_pf_hd256_sliding.cu"
D = 256
BF16_PEAK_TFLOPS = 989.0
DEFAULT = {"bn": 64, "kstages": 3, "vstages": 2, "preg": 56}
# (heads, kv heads, window, rows): Gemma-4 12B/26B/31B-class sliding layers and E4B-class.
CLASSES = [(16, 8, 1024, 1024), (16, 8, 1024, 4096), (16, 8, 1024, 8192),
           (8, 2, 512, 1000), (8, 2, 512, 2000)]


def creg(preg):
    # setmaxnreg pool: 384 threads x 168 at launch; the producer's release funds the consumers.
    return (168 + (168 - preg) * 128 // 256) // 8 * 8


def wgmma_inc():
    """Source of gen_attn_pf_hd256_wgmma.inc: one asm block per tile GEMM. Every descriptor is
    defined before wgmma.fence (a definition inside the stage serializes the wgmmas, ptxas C7513)
    without being hoisted out of the tile loop by the front end (that costs registers)."""
    def qk(n):
        r = n // 2
        acc = ", ".join(f"%{i}" for i in range(r))
        qa, kb, hi = r, r + 1, r + 2
        body = [".reg .pred pz, pa;", "setp.eq.u32 pz, 0, 1;", "setp.eq.u32 pa, 0, 0;",
                ".reg .b32 al<16>, bl<16>;", ".reg .b64 da<16>, db<16>;"]
        for kk in range(16):
            oa = (kk // 4) * 64 * 8 + (kk % 4) * 2
            ob = (kk // 4) * n * 8 + (kk % 4) * 2
            body += [f"add.u32 al{kk}, %{qa}, {oa};", f"add.u32 bl{kk}, %{kb}, {ob};",
                     f"mov.b64 da{kk}, {{al{kk}, %{hi}}};", f"mov.b64 db{kk}, {{bl{kk}, %{hi}}};"]
        body.append("wgmma.fence.sync.aligned;")
        body += [f"wgmma.mma_async.sync.aligned.m64n{n}k16.f32.bf16.bf16 {{{acc}}}, da{kk}, "
                 f"db{kk}, {'pz' if kk == 0 else 'pa'}, 1, 1, 0, 0;" for kk in range(16)]
        body.append("wgmma.commit_group.sync.aligned;")
        return (f"__device__ __forceinline__ void hd256_qk_n{n}(float* d, uint32_t qa, uint32_t kb,"
                f" uint32_t hi) {{\n    asm volatile(\n        \"{{\\n\"\n"
                + "".join(f'        "{line}\\n"\n' for line in body)
                + "        \"}\\n\"\n        : " + ", ".join(f'"+f"(d[{i}])' for i in range(r))
                + '\n        : "r"(qa), "r"(kb), "r"(hi)\n        : "memory");\n}\n')

    def pv(bn):
        # The descriptors come in as registers: this block is issued while the QK block is in
        # flight, so it must not define any wgmma input itself.
        r, ks = 128, bn // 16
        acc = ", ".join(f"%{i}" for i in range(r))
        body = ["wgmma.fence.sync.aligned;"]
        for kk in range(ks):
            a = ", ".join(f"%{r + 4 * kk + i}" for i in range(4))
            body.append(f"wgmma.mma_async.sync.aligned.m64n256k16.f32.bf16.bf16 {{{acc}}}, "
                        f"{{{a}}}, %{r + 4 * ks + kk}, 1, 1, 1, 1;")
        body.append("wgmma.commit_group.sync.aligned;")
        return (f"__device__ __forceinline__ void hd256_pv_bn{bn}(float* d, const uint32_t* a, "
                f"const uint64_t* vd) {{\n    asm volatile(\n        \"{{\\n\"\n"
                + "".join(f'        "{line}\\n"\n' for line in body)
                + "        \"}\\n\"\n        : " + ", ".join(f'"+f"(d[{i}])' for i in range(r))
                + "\n        : " + ", ".join(f'"r"(a[{i}])' for i in range(4 * ks))
                + ", " + ", ".join(f'"l"(vd[{i}])' for i in range(ks))
                + '\n        : "memory");\n}\n')

    head = ("// Generated by scripts/gen_kernels/attn_pf_hd256_sliding.py wgmma-inc; do not edit.\n"
            "// S = Q.K^T: 16 k-steps over K-major 128B-swizzled [4][rows][64] tiles.\n"
            "// O += P.V: P as register A fragments, V MN-major, LBO = one 64-column block.\n")
    return head + "".join(qk(n) for n in (32, 64)) + "".join(pv(bn) for bn in (32, 64))


def digest(cfg):
    """Generator identity of one config: the template sources plus the defines."""
    import hashlib
    h = hashlib.sha256()
    for path in (SOURCE, SOURCE.with_name("gen_attn_pf_hd256_wgmma.inc")):
        h.update(path.read_bytes())
    h.update(json.dumps(cfg, sort_keys=True).encode())
    return h.hexdigest()


def build(out, cfg):
    nvcc = os.environ.get("PLOW_NVCC", "/usr/local/cuda-12.9/bin/nvcc")
    cmd = [nvcc, "-ccbin", os.environ.get("PLOW_CXX", "/usr/bin/g++-14"), "-std=c++17",
           "-gencode", "arch=compute_90a,code=sm_90a", "-O3", "-cubin", "-Xptxas=-v",
           f"-I{REPO / 'runtime/common'}", f"-I{REPO / 'runtime/nvidia'}",
           f"-DGEN_BN={cfg['bn']}", f"-DGEN_KSTAGES={cfg['kstages']}",
           f"-DGEN_VSTAGES={cfg['vstages']}", f"-DGEN_PREG={cfg['preg']}",
           f"-DGEN_CREG={creg(cfg['preg'])}", "-o", str(out), str(SOURCE)]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode:
        raise RuntimeError(f"nvcc failed {cfg}:\n{res.stderr[-3000:]}")
    if "wgmma.mma_async instructions are serialized" in res.stderr:
        raise RuntimeError(f"ptxas serialized the wgmma pipeline for {cfg}")
    spill = sum(int(a) + int(b) for a, b in
                re.findall(r"(\d+) bytes spill stores, (\d+) bytes spill loads", res.stderr))
    return spill


# ---- GPU --------------------------------------------------------------------------------------

class Driver:
    def __init__(self):
        import torch
        torch.cuda.init()
        torch.zeros(1, device="cuda")
        self.torch = torch
        self.cu = ctypes.CDLL("libcuda.so.1")

    def check(self, rc, what):
        if rc:
            name = ctypes.c_char_p()
            self.cu.cuGetErrorName(rc, ctypes.byref(name))
            raise RuntimeError(f"{what}: {name.value}")

    def function(self, image, entry):
        mod, fn = ctypes.c_void_p(), ctypes.c_void_p()
        self.check(self.cu.cuModuleLoadData(ctypes.byref(mod), image), "cuModuleLoadData")
        self.check(self.cu.cuModuleGetFunction(ctypes.byref(fn), mod, entry.encode()), entry)
        return mod, fn

    def global_u32(self, mod, name):
        ptr, size = ctypes.c_uint64(), ctypes.c_size_t()
        self.check(self.cu.cuModuleGetGlobal_v2(ctypes.byref(ptr), ctypes.byref(size), mod,
                                                name.encode()), name)
        out = ctypes.c_uint32()
        self.check(self.cu.cuMemcpyDtoH_v2(ctypes.byref(out), ptr, ctypes.c_size_t(4)), "dtoh")
        return out.value

    def prepare(self, fn, block, smem):
        self.check(self.cu.cuFuncSetAttribute(fn, 8, ctypes.c_int(smem)), "max dynamic smem")
        n = ctypes.c_int()
        self.check(self.cu.cuOccupancyMaxActiveBlocksPerMultiprocessor(
            ctypes.byref(n), fn, ctypes.c_int(block), ctypes.c_size_t(smem)), "occupancy")
        if n.value != 1:
            raise RuntimeError(f"occupancy {n.value} != 1 CTA/SM")

    def launch(self, fn, grid, block, smem, args):
        buf = ctypes.create_string_buffer(bytes(args), len(args))
        params = (ctypes.c_void_p * 1)(ctypes.addressof(buf))
        stream = ctypes.c_void_p(self.torch.cuda.current_stream().cuda_stream)
        self.check(self.cu.cuLaunchKernel(fn, grid, 1, 1, block, 1, 1, smem, stream, params,
                                          None), "cuLaunchKernel")
        self._keep = (buf, params)

    def tmap_kv3(self, base, rows, heads, box_rows):
        m = (ctypes.c_uint8 * 128)()
        gd = (ctypes.c_uint64 * 3)(D, rows, heads)
        gs = (ctypes.c_uint64 * 2)(D * 2, rows * D * 2)
        bd = (ctypes.c_uint32 * 3)(64, box_rows, 1)
        es = (ctypes.c_uint32 * 3)(1, 1, 1)
        self.check(self.cu.cuTensorMapEncodeTiled(m, 9, 3, ctypes.c_void_p(base), gd, gs, bd, es,
                                                  0, 3, 2, 0), "tmap")
        return bytes(m)


def pack(fields):
    fmt = "<" + "".join({"p": "Q", "f": "f", "u": "I"}[k] for k, _ in fields)
    return struct.pack(fmt, *[v for _, v in fields])


class Case:
    """Packet-shaped buffers. Q/O [seq_q][H][256]; K/V [slots][KVH][kv_stride][256], position p
    of a request at ring row p & kv_mask; requests (q0, qlen, slot, kvlen) packed in order."""

    def __init__(self, drv, H, KVH, window, requests, seq_q=None, kv_stride=None, ring=True,
                 slots=None, seed=0, qscale=None):
        torch = drv.torch
        self.drv, self.H, self.KVH, self.window, self.requests = drv, H, KVH, window, requests
        real = requests[-1][0] + requests[-1][1]
        self.seq_q = seq_q or real
        need = max(kvlen for _, _, _, kvlen in requests)
        if ring:
            span = max((window or kvlen) + qlen - 1 for _, qlen, _, kvlen in requests)
            self.kv_stride = kv_stride or 1 << max(span - 1, 63).bit_length()
            self.kv_mask = self.kv_stride - 1
        else:
            self.kv_stride = kv_stride or need
            self.kv_mask = 0xFFFFFFFF
        slots = slots or (max(r[2] for r in requests) + 1)
        g = torch.Generator(device="cuda").manual_seed(seed)
        bf = torch.bfloat16
        qs = qscale if qscale is not None else D ** -0.5
        self.q = (torch.randn(self.seq_q, H, D, device="cuda", generator=g) * qs).to(bf)
        self.k = torch.zeros(slots, KVH, self.kv_stride, D, device="cuda", dtype=bf)
        self.v = torch.zeros_like(self.k)
        self.lin = []
        for q0, qlen, slot, kvlen in requests:
            kl = torch.randn(kvlen, KVH, D, device="cuda", generator=g).to(bf)
            vl = torch.randn(kvlen, KVH, D, device="cuda", generator=g).to(bf)
            pos = torch.arange(kvlen, device="cuda")
            if ring:
                keep = pos >= kvlen - self.kv_stride  # what the ring still holds
                rows = pos[keep] & self.kv_mask
                self.k[slot][:, rows] = kl[keep].transpose(0, 1)
                self.v[slot][:, rows] = vl[keep].transpose(0, 1)
            else:
                self.k[slot][:, :kvlen] = kl.transpose(0, 1)
                self.v[slot][:, :kvlen] = vl.transpose(0, 1)
            self.lin.append((kl, vl))
        self.o = torch.full((self.seq_q, H, D), float("nan"), device="cuda", dtype=bf)
        flat = [len(requests)] + [x for r in requests for x in r]
        self.req = torch.tensor(flat, device="cuda", dtype=torch.int32)
        self.entries = torch.zeros(4096 * 24, device="cuda", dtype=torch.uint8)
        self.counters = torch.zeros(4096, device="cuda", dtype=torch.int32)
        self.scratch = torch.zeros(16, device="cuda", dtype=torch.float32)

    def map_table(self):
        """The packed launch's per-slot table of GEN_TMAP_KV_PAIR blobs (K map, V map; rank 3
        {256, kv_stride, KVH}, box {64, 32, 1}, 128B swizzle), as the packet supplies it."""
        if not hasattr(self, "table"):
            torch = self.drv.torch
            slots = self.k.shape[0]
            self.desc = torch.zeros(slots * 256 + 128, device="cuda", dtype=torch.uint8)
            base = (self.desc.data_ptr() + 127) // 128 * 128
            off = base - self.desc.data_ptr()
            ptrs = []
            for s in range(slots):
                km = self.drv.tmap_kv3(self.k[s].data_ptr(), self.kv_stride, self.KVH, 32)
                vm = self.drv.tmap_kv3(self.v[s].data_ptr(), self.kv_stride, self.KVH, 32)
                self.desc[off + 256 * s:off + 256 * s + 256] = torch.tensor(
                    list(km + vm), dtype=torch.uint8, device="cuda")
                ptrs.append(base + 256 * s)
            self.table = torch.tensor(ptrs, dtype=torch.int64, device="cuda")
        return self.table.data_ptr()

    def gen_args(self, scale=1.0, tma=False):
        p = lambda t: ("p", t.data_ptr())
        mapkv = self.map_table() if tma else 0
        return pack([p(self.req), p(self.scratch), p(self.scratch), p(self.q), p(self.k),
                     p(self.v), p(self.o), ("p", mapkv), p(self.entries), p(self.counters),
                     p(self.counters), ("u", self.seq_q), ("u", 0), ("u", 0),
                     ("u", self.kv_stride), ("u", self.kv_mask), ("f", scale), ("u", self.H),
                     ("u", self.KVH), ("u", self.window), ("u", 0)])

    def role14_args(self, tma=True):
        """Role 14's direct entry (PlowHd256Gqa2Direct, 112 B); `tma` builds the per-slot
        descriptor-pair table the packet supplies (box 32 rows)."""
        mapkv = self.map_table() if tma else 0
        p = lambda t: ("p", t.data_ptr())
        return pack([p(self.req), p(self.scratch), p(self.scratch), p(self.q), p(self.k),
                     p(self.v), p(self.o), ("p", mapkv), p(self.entries), p(self.counters),
                     p(self.counters), ("u", self.seq_q), ("u", 0), ("u", 0),
                     ("u", self.kv_stride), ("u", self.kv_mask), ("f", 1.0)])

    def reference_error(self, scale=1.0):
        """rel-L2 of every valid output row vs fp32 attention over the linear K/V; also checks
        padded rows are zero and nothing is NaN."""
        torch = self.drv.torch
        num = den = 0.0
        g = self.H // self.KVH
        for (q0, qlen, slot, kvlen), (kl, vl) in zip(self.requests, self.lin):
            pos = torch.arange(kvlen - qlen, kvlen, device="cuda")[:, None]
            kv = torch.arange(kvlen, device="cuda")[None, :]
            mask = kv <= pos
            if self.window:
                mask &= pos - kv < self.window
            for h in range(self.H):
                q = self.q[q0:q0 + qlen, h].float()
                s = (q @ kl[:, h // g].float().T) * scale
                s.masked_fill_(~mask, float("-inf"))
                ref = s.softmax(-1) @ vl[:, h // g].float()
                got = self.o[q0:q0 + qlen, h].float()
                num += (got - ref).pow(2).sum().item()
                den += ref.pow(2).sum().item()
        real = self.requests[-1][0] + self.requests[-1][1]
        tail = self.o[real:]
        tail_ok = bool((tail == 0).all().item()) if tail.numel() else True
        finite = bool(torch.isfinite(self.o[:real]).all().item())
        return math.sqrt(num / den), tail_ok, finite


def graph_time(torch, fns, reps=7):
    for f in fns:
        f()
    torch.cuda.synchronize()
    g = torch.cuda.CUDAGraph()
    s = torch.cuda.Stream()
    s.wait_stream(torch.cuda.current_stream())
    with torch.cuda.stream(s):
        with torch.cuda.graph(g, stream=s):
            for f in fns:
                f()
    torch.cuda.synchronize()
    g.replay()
    torch.cuda.synchronize()
    ts = []
    for _ in range(reps):
        e0, e1 = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
        e0.record()
        g.replay()
        e1.record()
        e1.synchronize()
        ts.append(e0.elapsed_time(e1) * 1000 / len(fns))
    return sorted(ts)[len(ts) // 2]


class Kernel:
    def __init__(self, drv, cubin, tma=False):
        self.drv, self.tma = drv, tma
        self.mod, self.fn = drv.function(Path(cubin).read_bytes(), "plow_gen_flash_prefill_direct")
        self.block = drv.global_u32(self.mod, "plow_gen_block")
        self.smem = drv.global_u32(self.mod, "plow_gen_arena_bytes")
        drv.prepare(self.fn, self.block, self.smem)

    def __call__(self, case, scale=1.0):
        self.drv.launch(self.fn, 132, self.block, self.smem, case.gen_args(scale, self.tma))


class Role14:
    def __init__(self, drv, cubin, tma=True):
        self.drv, self.tma = drv, tma
        self.mod, self.fn = drv.function(Path(cubin).read_bytes(),
                                         "plow_sm90a_pfattn_hd256_gqa2_bkv32_direct")
        self.smem = drv.global_u32(self.mod, "plow_arena_bytes_pfattn_hd256_gqa2_bkv32")
        drv.prepare(self.fn, 256, self.smem)

    def __call__(self, case):
        if not hasattr(case, "_r14"):
            case._r14 = case.role14_args(self.tma)
        self.drv.launch(self.fn, 132, 256, self.smem, case._r14)


def flop(H, window, requests):
    total = 0
    for _, qlen, _, kvlen in requests:
        for i in range(qlen):
            p = kvlen - qlen + i
            total += min(p + 1, window) if window else p + 1
    return 4 * H * D * total


def check_cases():
    """(name, H, KVH, window, requests, kwargs): ragged, packed, chunked, ring wrap, windows
    smaller and larger than the prompt, padded rung tail, linear KV."""
    return [
        ("12B w1024 single 4096", 16, 8, 1024, [(0, 4096, 0, 4096)], {}),
        ("12B w1024 ragged 1000", 16, 8, 1024, [(0, 1000, 0, 1000)], {}),
        ("12B w1024 packed 3 + pad", 16, 8, 1024,
         [(0, 1000, 2, 3000), (1000, 1500, 0, 1500), (2500, 77, 1, 2125)], {"seq_q": 2688}),
        ("12B w1024 chunk wraps ring", 16, 8, 1024, [(0, 2048, 0, 9000)],
         {"kv_stride": 4096}),
        ("12B window > prompt", 16, 8, 1024, [(0, 300, 0, 300), (300, 513, 1, 513)], {}),
        ("E4B w512 1000", 8, 2, 512, [(0, 1000, 0, 1000)], {}),
        ("E4B w512 packed 2 + pad", 8, 2, 512, [(0, 700, 1, 700), (700, 1301, 0, 1301)],
         {"seq_q": 2048}),
        ("gqa2 h4/2 w100 tiny", 4, 2, 100, [(0, 1, 0, 1), (1, 65, 1, 70), (66, 3, 2, 200)], {}),
        ("no window linear kv", 16, 8, 0, [(0, 1500, 0, 1500)], {"ring": False}),
        ("w1024 linear kv chunked", 16, 8, 1024, [(0, 1024, 0, 3072)],
         {"ring": False, "kv_stride": 4096}),
        ("peaky logits w1024", 16, 8, 1024, [(0, 2048, 0, 2048)], {"qscale": 0.25}),
    ]


def cmd_check(a):
    drv = Driver()
    kerns = {"cp.async": Kernel(drv, a.cubin), "tma": Kernel(drv, a.cubin, True)}
    worst = 0.0
    ok_all = True
    for name, H, KVH, W, reqs, kw in check_cases():
        c = Case(drv, H, KVH, W, reqs, **kw)
        for mode, kern in kerns.items():
            c.o.fill_(float("nan"))
            kern(c)
            drv.torch.cuda.synchronize()
            err, tail, finite = c.reference_error()
            ok = err < 2e-2 and tail and finite
            ok_all &= ok
            worst = max(worst, err)
            print(f"{'PASS' if ok else 'FAIL'} {name} [{mode}]: rel_l2 {err:.2e} tail_zero {tail} "
                  f"finite {finite}", flush=True)
        if a.role14 and (H, KVH, W) == (16, 8, 1024) and kw.get("ring", True):
            r14 = Role14(drv, a.role14)
            c.o.fill_(float("nan"))
            r14(c)
            drv.torch.cuda.synchronize()
            e14, t14, f14 = c.reference_error()
            print(f"     role14 same case: rel_l2 {e14:.2e} tail_zero {t14} finite {f14}")
        del c
    print(f"worst rel_l2 {worst:.2e}; {'ALL PASS' if ok_all else 'FAILURES'}")
    return 0 if ok_all else 1


def bench_class(drv, fns, H, KVH, W, rows, role14=None, fa3=False):
    torch = drv.torch
    reqs = [(0, rows, 0, rows)]
    per = rows * (2 * H) * D * 2 + 2 * KVH * (1 << (W + rows - 2).bit_length()) * D * 2
    n = max(2, min(8, math.ceil(160e6 / per)))
    cases = [Case(drv, H, KVH, W, reqs, seed=s) for s in range(n)]
    fl = flop(H, W, reqs)
    out = {"floor_us": round(fl / BF16_PEAK_TFLOPS / 1e6, 1)}
    for name, k in fns.items():
        k(cases[0])
        torch.cuda.synchronize()
        err = cases[0].reference_error()[0]
        us = graph_time(torch, [(lambda c=c: k(c)) for c in cases])
        out[name] = {"us": round(us, 1), "rel_l2": float(f"{err:.2e}"),
                     "tflops": round(fl / us / 1e6)}
    if role14 is not None and (H, KVH, W) == (16, 8, 1024):
        for tma in (True,):
            r = Role14(drv, role14, tma)
            r(cases[0])
            torch.cuda.synchronize()
            err = cases[0].reference_error()[0]
            us = graph_time(torch, [(lambda c=c: r(c)) for c in cases])
            out["role14" + ("" if tma else "_cpasync")] = {
                "us": round(us, 1), "rel_l2": float(f"{err:.2e}"), "tflops": round(fl / us / 1e6)}
    if fa3:
        import flashinfer
        cu = torch.tensor([0, rows], device="cuda", dtype=torch.int32)
        fo = torch.empty(rows, H, D, device="cuda", dtype=torch.bfloat16)
        lin = [(c.q, c.lin[0][0], c.lin[0][1]) for c in cases]
        for be in ("fa3",):
            ws = torch.empty(256 << 20, dtype=torch.uint8, device="cuda")
            w = flashinfer.BatchPrefillWithRaggedKVCacheWrapper(ws, "NHD", backend=be)
            w.plan(cu, cu, H, KVH, D, causal=True, window_left=(W - 1) if W else -1,
                   q_data_type=torch.bfloat16, kv_data_type=torch.bfloat16, sm_scale=1.0)
            f = lambda b, w=w: w.run(b[0], b[1], b[2], out=fo)
            us = graph_time(torch, [(lambda b=b: f(b)) for b in lin])
            out["flashinfer_" + be] = {"us": round(us, 1), "tflops": round(fl / us / 1e6)}
    del cases
    torch.cuda.empty_cache()
    return out


def cmd_bench(a):
    drv = Driver()
    fns = {}
    for c in a.cubin:
        for tma in ((False, True) if a.tma else (False,)):
            fns[Path(c).stem + ("+tma" if tma else "")] = Kernel(drv, c, tma)
    classes = CLASSES if not a.classes else [tuple(int(x) for x in s.split(","))
                                             for s in a.classes]
    res = {}
    for H, KVH, W, rows in classes:
        key = f"h{H}kv{KVH}_w{W}_rows{rows}"
        res[key] = bench_class(drv, fns, H, KVH, W, rows, a.role14, a.fa3)
        print(key, json.dumps(res[key]), flush=True)
    if a.json:
        Path(a.json).write_text(json.dumps(res, indent=1) + "\n")


def sweep():
    """K/V ring depths that fit beside Q (2 x 32 KiB) in the 227 KiB arena, per score tile."""
    for bn, ks, vs in itertools.product((64, 32), (2, 3, 4, 6), (2, 3, 4)):
        size = 2 * 64 * 512 + (ks + vs) * bn * 512 + 1024 + 8 * (4 + 2 * ks + 2 * vs)
        if size <= 227 * 1024 and vs <= ks:
            yield {"bn": bn, "kstages": ks, "vstages": vs, "preg": 56}


def class_key(H, KVH, W, rows):
    return f"h{H}kv{KVH}_w{W}_rows{rows}"


def packed_check(drv, kern):
    """Three chunked requests in one padded launch with a wrapping ring: slot order, KV offset,
    zeroed tail."""
    c = Case(drv, 16, 8, 1024, [(0, 1000, 2, 3000), (1000, 1500, 0, 1500), (2500, 77, 1, 9000)],
             seq_q=2688, kv_stride=4096)
    kern(c)
    drv.torch.cuda.synchronize()
    err, tail, finite = c.reference_error()
    return {"rel_l2": float(f"{err:.2e}"), "tail_zero": tail, "finite": finite}


def tune_row(log=print):
    """Sweep every config over every shape class with the packet's KV maps (the TMA staging the
    role runs in-model), pick the least total time, and return the catalog row (minus signature
    and object) for build_catalog.py's table."""
    drv = Driver()
    trials = []
    with tempfile.TemporaryDirectory() as tmp:
        for cfg in sweep():
            out = Path(tmp) / "k.cubin"
            try:
                spill = build(out, cfg)
            except RuntimeError as e:
                log(f"{cfg}: build failed: {str(e).splitlines()[0]}")
                continue
            if spill:
                log(f"{cfg}: {spill} spill bytes, skipped")
                continue
            kern = Kernel(drv, out, tma=True)
            res = {class_key(*cl): bench_class(drv, {"gen": kern}, *cl)["gen"] | {
                "floor_us": round(flop(cl[0], cl[2], [(0, cl[3], 0, cl[3])]) /
                                  BF16_PEAK_TFLOPS / 1e6, 1)} for cl in CLASSES}
            pack = packed_check(drv, kern)
            ok = (pack["tail_zero"] and pack["finite"] and pack["rel_l2"] < 1e-2
                  and all(v["rel_l2"] < 1e-2 for v in res.values()))
            log(f"{cfg}: {json.dumps(res)} packed {pack}")
            if ok:
                trials.append((cfg, res, pack))
    if not trials:
        raise RuntimeError("attn_pf_hd256_sliding: no valid config")
    best = min(trials, key=lambda t: sum(v["us"] for v in t[1].values()))
    classes = {}
    for cl in CLASSES:
        key = class_key(*cl)
        meas = [{"config": c, **r[key]} for c, r, _ in trials]
        classes[key] = {"best": min(meas, key=lambda m: m["us"])["config"], "measured": meas}
    return {"config": best[0], "body_sha256": digest(best[0]),
            "selection": "min total us over classes, TMA staging", "classes": classes,
            "packed_check": best[2], "spill_bytes": 0}


def catalog_build(cfg, out):
    """build_catalog.py hook: compile one config, return its generator digest."""
    if build(out, cfg):
        raise RuntimeError(f"attn_pf_hd256_sliding {cfg} spills")
    return digest(cfg)


def cmd_tune(a):
    row = tune_row()
    Path(a.out).write_text(json.dumps(row, indent=1) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build")
    b.add_argument("out")
    b.add_argument("--config", default="")
    c = sub.add_parser("check")
    c.add_argument("cubin")
    c.add_argument("--role14")
    be = sub.add_parser("bench")
    be.add_argument("cubin", nargs="+")
    be.add_argument("--role14")
    be.add_argument("--fa3", action="store_true")
    be.add_argument("--tma", action="store_true", help="also run each cubin with KV maps")
    be.add_argument("--classes", nargs="*")
    be.add_argument("--json")
    t = sub.add_parser("tune")
    t.add_argument("out")
    sub.add_parser("wgmma-inc")
    a = ap.parse_args()
    if a.cmd == "wgmma-inc":
        SOURCE.with_name("gen_attn_pf_hd256_wgmma.inc").write_text(wgmma_inc())
        return 0
    if a.cmd == "build":
        cfg = dict(DEFAULT)
        for kv in filter(None, a.config.split(",")):
            k, v = kv.split("=")
            cfg[k] = int(v)
        print(f"spill bytes {build(a.out, cfg)}")
        return 0
    return {"check": cmd_check, "bench": cmd_bench, "tune": cmd_tune}[a.cmd](a) or 0


if __name__ == "__main__":
    sys.exit(main())
